Cleanup

diff --git a/ydm b/ydm
--- a/ydm
+++ b/ydm
@@ -12,22 +12,20 @@
 # Parse input, including optional flags
 quick=0     # 1 means skip metadata, 2 means skip normalization
 mp3=false   # mp3 or m4a by default?
-debug=false # debug mode
 metadata=true   # by default, retrieve metadata and noarmalize
 classical=false # different folder for classical music
-flags_norm="-v -t -23" # normalize to default of -23
+flags_norm="-t -23" # normalize to default of -23
 $mp3 && ext_new="mp3" || ext_new="m4a"
 while [ $# -gt 0 ]; do
   case $1 in
+    -3|--mp3)        mp3=true  ;; # m4a is better format so generally want to avoid this
+    -4|--m4a|--aac)  mp3=false ;;
     -q|--quick)      quick=1 ;;
     -Q|--very-quick) quick=2 ;;
-    -cl|--classical)   classical=true; ;;
-    -c|--cut-leading)  lead=$2;  shift; ;; # cut leading time, seconds
-    -C|--cut-trailing) trail=$2; shift; ;; # cut trailing time, seconds
-    -3|--mp3)       mp3=true;        ;; # m4a is better format so generally want to avoid this
-    -4|--m4a|--aac) mp3=false;       ;;
-    -d|--debug)     debug=true;      ;; # keep all the intermediate files along the way
-    --strict|--genreonly|--confirm|--forget|--debug) flags_metadata+="$1 "; ;;
+    -cl|--classical) classical=true; ;;
+    -c=*|--cut-leading)  lead=${1#*=} ;; # cut leading time, seconds
+    -C=*|--cut-trailing) trail=${1#*=} ;; # cut trailing time, seconds
+    --strict|--confirm|--forget|--verbose) flags_metadata+="$1 "; ;;
     -[-a-zA-Z0-9]*) echo "Error: Unknown flag \"$1\"." && exit 1; ;;
     http*) url="$1"; ;;    # youtube url
     *)     name+=" $1"; ;; # so user can specify filename without spaces
@@ -80,27 +78,23 @@ if [ ! -z "$rejects" ] && compgen -G "$rejects/$name.*" &>/dev/null; then
 fi
 
 # A few basic settings
+# TODO: Support for downloading entire playlists or albums
 path_template="$directory/$name-download.%(ext)s" # see youtube-dl help info; just picks whatever extension
 path_normalized="$directory/$name-normalized.$ext_new"
 path_intermediate="$directory/$name-normalized.wav" # sometimes unused
 path_new="$directory/$name.$ext_new"
-flags="-f bestaudio --no-playlist"
+flags="-q -f bestaudio --no-playlist"
 
 #------------------------------------------------------------------------------#
 # Download, using youtube-dl
 #------------------------------------------------------------------------------#
-# youtube-dl -f bestaudio[ext=m4a] --no-playlist --prefer-ffmpeg --embed-thumbnail "$url" -o "$path_old"
-# youtube-dl -f bestaudio[ext=m4a] -t "$name" --metadata-from-title "%(artist)s - %(title)s" --no-playlist --prefer-ffmpeg --embed-thumbnail "$url" -o "$path_old"
-echo "Determining filename." && sleep 0.5
-echo $path_template
-path_old="$(youtube-dl --get-filename $flags "$url" -o "$path_template")" # no playlist, in case user provides playlist URL
-[ -z "$path_old" ] && echo "Error: Could not get name." && exit 1
-ext_old="${path_old##*.}"
-echo "Downloading." && sleep 0.5
+echo "Determining filename."
+path="$(youtube-dl --get-filename $flags "$url" -o "$path_template")" # no playlist, in case user provides playlist URL
+[ -z "$path" ] && echo "Error: Could not get name." && exit 1
+ext="${path##*.}"
+echo "Downloading."
 youtube-dl $flags "$url" -o "$path_template" # no playlist, in case user provides playlist URL
 [ $? -ne 0 ] && echo "Error: Download failed." && exit 1
-$debug && cp "$path_old" "$directory/$name-raw.$ext_old" # original file, not normalized
-# Bail
 [ $quick -ge 2 ] && exit 0
 
 #------------------------------------------------------------------------------#
@@ -109,43 +103,37 @@ $debug && cp "$path_old" "$directory/$name-raw.$ext_old" # original file, not no
 #   Refers to the target average loudness units for track; this
 #   will prevent clipping of sounds up to 26dB above this average.
 #   See: https://www.pro-tools-expert.com/home-page/2016/9/6/video-mastering-using-lufs
-# * Might consider using iTunes default bitrate of 256kbs
-#   See: https://lifehacker.com/5810575/does-bitrate-really-make-a-difference-in-my-music
-#   But it seems otherwise, will be recompressed into roughly the original bitrate; probably
-#   doesn't make sense to decompress a compressed format, then save it in a higher resolution.
+# * Note default iTunes default bitrate is 256kbs. This step will save
+#   file with output bitrate roughly matching original bitrate. Save into m4a
+#   because it is better, more efficient format than mp3.
 #------------------------------------------------------------------------------#
-if $mp3; then # tried with and without intermediary, still fails
-  echo "Normalizing volume, outputing to mp3." && sleep 0.5
-  # ffmpeg-normalize $flags_norm "$flags_trim" -f -c:a libmp3lame -o "$path_normalized" "$path_old"
-  ffmpeg-normalize "$path_old" $flags_norm "$flags_trim" -f -c:a libmp3lame -o "$path_normalized"
-  # echo "Generating intermediate file." && sleep 0.5
-  # ffmpeg-normalize "$path_old" -v -f -o "$path_intermediate"
-  # echo "Normalizing volume, outputing to mp3." && sleep 0.5
+# Save to mp3
+# TODO: Fix this, tried with and without intermediary but still fails
+if $mp3; then
+  echo "Normalizing volume, outputing to mp3."
+  ffmpeg-normalize "$path" $flags_norm "$flags_trim" -f -c:a libmp3lame -o "$path_normalized"
+  # echo "Generating intermediate file."
+  # ffmpeg-normalize "$path" -v -f -o "$path_intermediate"
   # ffmpeg -y -i "$path_intermediate" -c:a libmp3lame "$path_normalized"
   [ $? -ne 0 ] && echo "Error: Normalization failed." && exit 1
-  # ! $debug && rm "$path_intermediate"
-else # builtin aac thing sucks; make sure to brew install ffmpeg with option --with-fdk-aac
-  echo "Normalizing volume, outputing to m4a." && sleep 0.5
-  # ffmpeg-normalize $flags_norm "$flags_trim" -f -c:a libfdk_aac -o "$path_normalized" "$path_old"
-  ffmpeg-normalize "$path_old" $flags_norm "$flags_trim" -f -c:a libfdk_aac -o "$path_normalized"
+# Save to m4a
+# Builtin aac thing sucks; make sure to brew install ffmpeg with option --with-fdk-aac
+else
+  echo "Normalizing volume, outputing to m4a."
+  ffmpeg-normalize "$path" $flags_norm "$flags_trim" -f -c:a libfdk_aac -o "$path_normalized"
+  # ffmpeg-normalize $flags_norm "$flags_trim" -f -c:a libfdk_aac -o "$path_normalized" "$path"
+  # ffmpeg-normalize "$path" $flags_norm "$flags_trim" -f -o "${path_normalized%.*}.wav" # repeat, uncompressed
   [ $? -ne 0 ] && echo "Error: Normalization failed." && exit 1
 fi
-# Repeat for debugging
-# Move files around, and potentially delete outdated files
-if $debug; then
-  ffmpeg-normalize "$path_old" $flags_norm "$flags_trim" -f -o "${path_normalized%.*}.wav" # repeat, uncompressed
-  cp "$path_normalized" "$path_new"
-else
-  rm "$path_old"
-  mv "$path_normalized" "$path_new"
-fi
+rm "$path"
+mv "$path_normalized" "$path_new"
 # Bail
 [ $quick -ge 1 ] && exit 0
 
 #------------------------------------------------------------------------------#
 # Change metadata using python function
 #------------------------------------------------------------------------------#
-echo "Adding metadata." && sleep 0.5
+echo "Adding metadata."
 ydm-metadata $flags_metadata --url="$url" "$path_new"
 [ $? -ne 0 ] && echo "Error: Metadata script failed." && exit 1
 $debug && cp "$path_new" "${path_new%.*}-metadata.${ext_new}"
